api-version: 1.19
name: WBFCore
main: alpine.wbf.core.Core
version: 2.5 beta
authors: [ ALPINE ]
description: Core Plugin for survival server [WBF]
softdepend: [LuckPerms]
commands:
  help:
    description: Pokazuje wszystkie dostępne dla Ciebie komendy
  discord:
    description: Link do naszego discorda
  openinv:
    description: Otwiera ekwipunek gracza
    permission: wbfCore.admin.open.inv
  openechest:
    description: Otwiera enderchest gracza
    permission: wbfCore.admin.open.enderchest
  craft:
    description: Otwiera przenośny crafting table
    permission: wbfCore.craft
  spawn:
    description: Teleportuje na spawn
#    permission: wbfCore.teleport.spawn
  setspawn:
    description: Zapisuje lokalizacje spawnu
    permission: wbfCore.teleport.setspawn
  home:
    description: Zarządzenie własnymi teleportami
    permission: wbfCore.teleport.home
  sethome:
    description: Dodawanie własnego teleportu
    permission: wbfCore.teleport.home
  time:
    description: Ustawianie czasu na serwerze
    permission: wbfCore.time
  weather:
    description: Ustawianie pogody na serwerze
    permission: wbfCore.weather
  chatoff:
    description: Ustawianie pogody na serwerze
    permission: wbfCore.admin.chatoff